from .shared_arch import shared
from .simple import SimpleAgent
from .compo import CompoNetAgent
from .packnet import PackNetAgent
from .prognet import ProgressiveNetAgent
from .cka_rl import CkaRlAgent
from .masknet import MaskNetAgent
from .cbpnet import CbpAgent
from .crelus import CReLUsAgent